config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("items/", include("items.urls", namespace="items")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from items import views as item_views

app_name = "core"

urlpatterns = [
    path("", item_views.HomeView.as_view(), name="home"),
]

items/urls.py
from django.urls import path
from . import views

app_name = "items"

urlpatterns = [
    path("<int:pk>/", views.ItemDetail.as_view(), name="detail"),
    path("create/", views.CreateItemView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditItemView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.ItemPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:item_pk>/", views.add_fav, name="add-favs"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

templates/partials/footer.html
<footer>
    &copy; 블라블라
</footer>

templates/partials/menu.html
<div class="border-b-2 mb-5">
    <ul class="flex items-center text-sm font-medium h-full">
        <li class="nav_link"><a href="#">Best</a></li>
        <li class="nav_link"><a href="#">Outer</a></li>
        <li class="nav_link"><a href="#">Top</a></li>
        <li class="nav_link"><a href="#">Dress</a></li>
    </ul>
</div>

templates/partials/nav.html
<div class="flex border-b justify-between">
    <div class="flex items-center w-1/8 border-r-2 px-3">
        <a href="{% url "core:home" %}">
            HOME
        </a>
    </div>

    <ul class="flex items-center text-sm font-medium h-full">
        {% if user.is_authenticated %}
        <li class="nav_link"><a href="{% url 'users:logout' %}">Log out</a></li>
        <li class="nav_link"><a href="{% url 'users:see-favs' %}">Favs
                {% if user.lists.items.count != '' %}
                ({{user.lists.items.count}})
                {% endif %}</a>
        </li>
        <li class="nav_link"><a href="{% url 'orders:detail' %}">Order</a></li>
        <li class="nav_link"><a href="#">MyPage</a></li>
        {% else %}
        <li class="nav_link"><a href="{% url 'users:login' %}">Log in</a></li>
        <li class="nav_link"><a href="{% url 'users:signup' %} ">Sign Up</a></li>
        {% endif %}
    </ul>
</div>

templates/partials/search.html
<div class="flex justify-center items-center mr-10">
    <a href="#">장바구니</a>
    <form method="get" action="#" class="w-9/12">
        <input class="search-box border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-md w-64 shadow-md hover:shadow-lg focus:outline-none" name="search" placeholder="Search" />
    </form>
</div>