config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("items/", include("items.urls", namespace="items")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from items import views as item_views

app_name = "core"

urlpatterns = [
    path("", item_views.HomeView.as_view(), name="home"),
]

items/urls.py
from django.urls import path
from . import views

app_name = "items"

urlpatterns = [
    path("<int:pk>/", views.ItemDetail.as_view(), name="detail"),
    path("create/", views.CreateItemView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditItemView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.ItemPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
]

templates/mixins/item_card.html
<div class="w-1/4 mb-10 px-4 overflow-hidden">
    <a href="{% url 'items:detail' item.pk %}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2 " style="background-image: url({{item.thumbnail}})"></div>
        <div>
            <span class="text-sm text-gray-600 block truncate mb-2">{{item.name}}</span>
            <span class="text-black w-11/12 block truncate">{{item.price}}원</span>
        </div>
    </a>
</div>