config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("items/", include("items.urls", namespace="items")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from items import views as item_views

app_name = "core"

urlpatterns = [
    path("", item_views.HomeView.as_view(), name="home"),
]

items/urls.py
from django.urls import path
from . import views

app_name = "items"

urlpatterns = [
    path("<int:pk>/", views.ItemDetail.as_view(), name="detail"),
    path("create/", views.CreateItemView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditItemView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.ItemPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:item_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("<int:item_pk>/addorder/", views.create_order, name="add-order"),
    path("order/", views.OrderList.as_view(), name="detail"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:item_pk>/", views.add_fav, name="add-favs"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

items/models.py
from django.db import models
from core import models as core_models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Tag(models.Model):
    tag_name = models.CharField(max_length=1024)
    
    def __str__(self):
        return self.tag_name
    
class Category(models.Model):
    category_name = models.CharField(max_length=1024)
    
    def __str__(self):
        return self.category_name
    
class Option(models.Model):
    name = models.CharField(max_length=1024)
    extra_money = models.IntegerField()
    item = models.ForeignKey("Item", related_name="options", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
class Item(core_models.TimeStampedModel):
    name = models.CharField(max_length=80)
    shorten_description = models.TextField(blank=True)
    tag = models.ManyToManyField("Tag", related_name="items", blank=True)
    category = models.ManyToManyField("Category", related_name="items", blank=True)
    status = models.BooleanField(default=True)
    price = models.IntegerField()
    description = RichTextUploadingField(null=True, blank=True)
    count = models.IntegerField()
    owner = models.ForeignKey("users.User", related_name="items", on_delete=models.CASCADE)
    
    status.boolean = True
    
    def __str__(self):
        return self.name
    
    def thumbnail(self):
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None
        
    def get_option(self):
        try:
            option, = self.options.all()
            return option
        except ValueError:
            return None
    
class Photo(models.Model):
    file = models.ImageField(upload_to="item_photos")
    item = models.ForeignKey("Item",related_name="photos" , on_delete=models.CASCADE, null = True, blank=True)

items/forms.py
from django import forms
from . import models

class CreateItemForm(forms.ModelForm):
    class Meta:
        model = models.Item
        fields=(
            "name",
            "shorten_description",
            "tag",
            "category",
            "status",
            "price",
            "description",
            "count",
        )
        
    def save(self, *args, **kwargs):
        item = super().save(commit=False)
        return item
    
class CreatePhotoForm(forms.ModelForm):
    
    class Meta:
        model = models.Photo
        fields = (
            "file",
        )
        
    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        item = models.Item.objects.get(pk=pk)
        photo.item = item
        photo.save()
    

items/views.py
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView, FormView, UpdateView
from . import models, forms
from users import models as user_models

# Create your views here.
class HomeView(ListView):
    
    model = models.Item
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "items"
    
class ItemDetail(DetailView):
    
    model = models.Item
    context_object_name = "item"
    
class CreateItemView(FormView):
    
    form_class = forms.CreateItemForm
    template_name = "items/item_create.html"
    
    def form_valid(self, form):
        item = form.save()
        item.owner = self.request.user
        item.save()
        form.save_m2m()
        return redirect(reverse("items:photos", kwargs={'pk': item.pk}))
    
class EditItemView(UpdateView):
    
    model = models.Item
    template_name = "items/item_edit.html"
    fields = (
        "name",
        "shorten_description",
        "tag",
        "category",
        "status",
        "price",
        "description",
        "count",
    )
    
    def get_success_url(self):
        item_pk = self.kwargs.get("pk")
        return reverse("items:detail", kwargs={"pk":item_pk})
    
class ItemPhotosView(DetailView):
    
    model = models.Item
    template_name = "items/item_phtos.html"
    
    def get_object(self, queryset=None):
        item = super().get_object(queryset=queryset)
        if item.owner.pk != self.request.user.pk:
            raise Http404()
        return item

class AddPhotoView(FormView):
    
    template_name = "items/photo_create.html"
    form_class = forms.CreatePhotoForm
    
    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        form.save(pk)
        # messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("items:photos", kwargs={'pk':pk}))
    
@login_required  
def delete_photo(request, item_pk, photo_pk):
    user = request.user
    try:
        item = models.Item.objects.get(pk=item_pk)
        if item.owner.pk != user.pk:
            # messages.error(request, "Can't delete that photo")
            print("Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            # messages.success(request, "Photo Deleted")
            print("Photo Deleted")
        return redirect(reverse("items:photos", kwargs={'pk':item_pk}))
    except models.Item.DoesNotExist:
        return redirect(reverse("core:home"))
    
class EditPhotoView(UpdateView):
    
    model = models.Photo
    template_name = "items/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("file",)
    
    def get_success_url(self):
        item_pk = self.kwargs.get("item_pk")
        return reverse("items:photos", kwargs={"pk":item_pk})

templates/items/item_create.html
{% extends "base.html" %}

{% block page_title %}
    상품 추가
{% endblock page_title %}

{% block content %}
    <div class="container flex justify-center mx-auto bg-gray-200 rounded-lg text-bold">
        <form method="POST">
            <div class="my-5">
                {% csrf_token %}
                {{form.media}}
                {{form.as_p}}
            </div>
            <button class="w-full bg-green-300 rounded-lg py-5 my-3 text-xl hover:bg-green-500">다음</button>
        </form>
    </div>
{% endblock content %}

templates/items/item_detail.html
{% extends "base.html" %}
{% load on_favs %}

{% block page_title %}
    {{item.name}}
{% endblock page_title %}

{% block content %}

    <div class="w-3/4 justify-center mx-auto">
        <div class="flex justify-center mb-5 border-b">
            <div>
                <div>
                    <div class="h-64 w-64 bg-cover rounded-md" style="background-image:url({{item.thumbnail}})"></div>
                </div>
            </div>

            <div class="ml-20 w-2/5">

                <div class="flex items-center mb-3">
                    <span class="w-40">PRICE</span>
                    <span class="font-semibold">{{item.price}}원</span>
                </div>

                <div class="flex items-center mb-3">
                    <span class="w-40">COMMENT</span>
                    <span class="text-sm w-64">{{item.shorten_description}}</span>
                </div>

                <form method = "POST" action = "{% url 'orders:add-order' item.pk %}">
                    <div class="flex items-center mb-3">
                        <span class="w-40">OPTION</span>
                        {% csrf_token %}
                        <select class="bg-gray-200 rounded-md" name="option">
                            <option selected="selected" disabled>옵션 선택</option>
                            <option disabled>-----------</option>
                            {% for option in item.options.all %}
                                <option value="{{option.pk}}">{{option.name}} +{{option.extra_money}}원</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="flex justify-center mb-5">
                        <button class="item_btn bg-gray-700 hover:bg-gray-900 text-white">주문하기</button></form>
                        <a class="item_btn bg-gray-200 hover:bg-gray-400" href="#">장바구니</a>
                        <a class="item_btn bg-gray-200 hover:bg-gray-400" href="{% url 'items:edit' item.pk %}">편집</a>
                        {% if user.is_authenticated %}
                            {% on_favs item as on_favs_boolean %}
                            {% if on_favs_boolean %}
                            {% else %}
                                <a class="item_btn bg-gray-200 hover:bg-gray-400" href="{% url 'users:add-favs' item.pk %}">찜하기</a>
                            {% endif %}
                        {% endif %}
                    </div>
            </div>
        </div>

        <div class="mb-5">
            <div>{{item.description|safe}}</div>
        </div>

        <ul class="flex items-center text-sm font-medium">
            <li class="nav_link cursor-pointer"><a>Review</a></li>
            <li class="nav_link cursor-pointer"><a>QnA</a></li>
            <li class="nav_link cursor-pointer"><a>MyPage</a></li>
        </ul>

        <div class="border-t">
            {% for review in item.reviews.all %}
                <div>
                    <p>{{review.title}} | {{review.content}} | {{review.user.name}} | {{review.created|date:'F Y'}}</p>
                </div>
            {% endfor %}
        </div>

        <div class="border-t">
            <form action="{% url 'reviews:create' item.pk %}" method="POST" >
                {% csrf_token %}
                title <input name="title"/>
                content <input name="content"/>
                <button class="w-full bg-gray-300 rounded-lg py-3 my-3 text-xl hover:bg-gray-500">리뷰 작성</button>
            </form>
        </div>

    </div>
{% endblock content %}

templates/items/item_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Item
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container flex flex-col justify-center mx-auto bg-gray-200 rounded-lg text-bold">
        <div class="my-5">
            {% csrf_token %}
            {{form.media}}
            {% include 'mixins/item/item_form.html' with form=form cta="Update Item" %}
            <div class="mt-5">
                <a href="{% url 'items:photos' item.pk %}" class="text-teal-500 font-medium">Edit Photos</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/items/item_list.html
{% extends "base.html" %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}

    <div class="container mx-auto pb-10">

        <div class="flex flex-wrap -mx-40 mb-10 justify-center">
            {% for item in items  %}
                {% include 'mixins/item_card.html' with item=item %}
            {% endfor %}
        </div>
        
        <div class="flex items-center justify-center mx-auto container">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>
            {% endif %}

            <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

            {% if page_obj.has_next  %}
                <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %}
        </div>

        <a class="item_btn bg-gray-300 rounded-sm hover:bg-gray-500" href="{% url 'items:create' %}">상품 추가</a>
        
    </div>
    
{% endblock content %}

templates/items/item_phtos.html
{% extends 'base.html' %}

{% block page_title %}
    Edit Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">

        <div class="my-10 w-full">
            <a href="{% url 'items:add-photo' item.pk %}" class="rounded-md bg-teal-500 w-40 text-center text-xl py-3 px-3 hover:bg-teal-700">Upload Photo</a>
        </div>

        {% for photo in item.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">

                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    {% comment %} <span class="ml-5 text-xl">{{photo.caption}}</span> {% endcomment %}
                </div>

                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-teal-500" href="{% url 'items:edit-photo' item.pk photo.pk %}">Edit</a>
                    <a class="btn-link bg-red-600" href="{% url 'items:delete-photo' item.pk photo.pk %}">Delete</a>
                </div>

            </div>
        {% endfor %}

        <div class="flex justify-between mt-5">
            <a href="{% url 'items:edit' item.pk %}" class="text-red-500 font-medium text-xl">이전</a>
            <a href="{% url 'core:home' %}" class="text-teal-500 font-medium text-xl">완료</a>
        </div>

    </div>
{% endblock content %}

templates/items/photo_create.html
{% extends 'base.html' %}

{% block page_title %}
    Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

            {% include 'mixins/item/item_form.html' with form=form cta="Upload Photo" %}

    </div>
{% endblock content %}

templates/items/photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

            {% include 'mixins/item/item_form.html' with form=form cta="Update Photo" %}

    </div>
{% endblock content %}